title: Restrung
description: 无言独上西楼
author: XIAO LIJIA
avatar: /logo.png
email: 2530183231@qq.com

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
twitter:
  username: RestrungX
  card: summary
logo: logo.png
social:
  name: RestrungX
  links:
    - https://twitter.com/RestrungX
    - https://github.com/RestrungX
google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: zh-Hans
